# Premier League PPI Scraper
Created Tuesday, 29 Mar 2016

In [1]:
# Import libraries
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from time import time
from urllib.request import urlopen

## EA Sports Player Performance Index

In [18]:
# Get PPI data from url
pl_ppi = "http://www.premierleague.com/en-gb/players/ea-sports-player-performance-index.html"
content = urlopen(pl_ppi).read()
soup = BeautifulSoup(content, "lxml")
trs = soup.find("div", attrs={"class": "tableView"}).find("table").findAll("tr")

In [22]:
for tr in trs:
    cells = row.findChildren('td')
    for cell in cells:
        value = cell.string
        print("Cell value: %s" % value)

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

Cell value: 20
Cell value: None
Cell value: 20
Cell value: Marko Arnautovic
Cell value: STK
Cell value: Forward
Cell value: 29
Cell value: 2417
Cell value: 16
Cell value: 277
Cell value: 18
Cell value: 189
Cell value: 14
Cell value:
                            466

In [12]:
# TODO: For each tr in trs, write each td to a row in a data frame.
tables = soup.findChildren('table')
my_table = tables[0]
rows = my_table.findChildren(['th', 'tr'])
for row in rows:
    cells = row.findChildren('td')
    for cell in cells:
        value = cell.string
        print("The value in this cell is %s" % value)

The value in this cell is 1
The value in this cell is None
The value in this cell is 1
The value in this cell is Harry Kane
The value in this cell is TOT
The value in this cell is Forward
The value in this cell is 32
The value in this cell is 2829
The value in this cell is 28
The value in this cell is 460
The value in this cell is 29
The value in this cell is 439
The value in this cell is 27
The value in this cell is
                            899

The value in this cell is 2
The value in this cell is None
The value in this cell is 2
The value in this cell is Riyad Mahrez
The value in this cell is LEI
The value in this cell is Midfielder
The value in this cell is 31
The value in this cell is 2546
The value in this cell is 27
The value in this cell is 378
The value in this cell is 24
The value in this cell is 474
The value in this cell is 32
The value in this cell is
                            851

The value in this cell is 3
The value in this cell is None
The value in this cell is 3
The value in this cell is Jamie Vardy
The value in this cell is LEI
The value in this cell is Forward
The value in this cell is 32
The value in this cell is 2813
The value in this cell is 25
The value in this cell is 444
The value in this cell is 28
The value in this cell is 365
The value in this cell is 23
The value in this cell is
                            809

The value in this cell is 4
The value in this cell is None
The value in this cell is 5
The value in this cell is Mesut Özil
The value in this cell is ARS
The value in this cell is Midfielder
The value in this cell is 29
The value in this cell is 2519
The value in this cell is 23
The value in this cell is 346
The value in this cell is 23
The value in this cell is 317
The value in this cell is 23
The value in this cell is
                            662

The value in this cell is 5
The value in this cell is None
The value in this cell is 6
The value in this cell is Christian Eriksen
The value in this cell is TOT
The value in this cell is Midfielder
The value in this cell is 29
The value in this cell is 2398
The value in this cell is 23
The value in this cell is 345
The value in this cell is 23
The value in this cell is 310
The value in this cell is 22
The value in this cell is
                            655

The value in this cell is 6
The value in this cell is None
The value in this cell is 4
The value in this cell is Romelu Lukaku
The value in this cell is EVE
The value in this cell is Forward
The value in this cell is 30
The value in this cell is 2604
The value in this cell is 22
The value in this cell is 337
The value in this cell is 21
The value in this cell is 315
The value in this cell is 22
The value in this cell is
                            652

The value in this cell is 7
The value in this cell is None
The value in this cell is 7
The value in this cell is Odion Ighalo
The value in this cell is WAT
The value in this cell is Forward
The value in this cell is 31
The value in this cell is 2611
The value in this cell is 20
The value in this cell is 340
The value in this cell is 21
The value in this cell is 288
The value in this cell is 19
The value in this cell is
                            627

The value in this cell is 8
The value in this cell is None
The value in this cell is 10
The value in this cell is Dimitri Payet
The value in this cell is WHU
The value in this cell is Midfielder
The value in this cell is 24
The value in this cell is 2042
The value in this cell is 24
The value in this cell is 262
The value in this cell is 22
The value in this cell is 321
The value in this cell is 27
The value in this cell is
                            583

The value in this cell is 9
The value in this cell is None
The value in this cell is 8
The value in this cell is Ross Barkley
The value in this cell is EVE
The value in this cell is Midfielder
The value in this cell is 30
The value in this cell is 2616
The value in this cell is 19
The value in this cell is 317
The value in this cell is 20
The value in this cell is 261
The value in this cell is 19
The value in this cell is
                            578

The value in this cell is 10
The value in this cell is None
The value in this cell is 9
The value in this cell is Dele Alli
The value in this cell is TOT
The value in this cell is Midfielder
The value in this cell is 30
The value in this cell is 2217
The value in this cell is 19
The value in this cell is 265
The value in this cell is 19
The value in this cell is 312
The value in this cell is 20
The value in this cell is
                            577

The value in this cell is 11
The value in this cell is None
The value in this cell is 11
The value in this cell is Sergio Agüero
The value in this cell is MCI
The value in this cell is Forward
The value in this cell is 24
The value in this cell is 1865
The value in this cell is 23
The value in this cell is 336
The value in this cell is 28
The value in this cell is 217
The value in this cell is 18
The value in this cell is
                            553

The value in this cell is 12
The value in this cell is None
The value in this cell is 12
The value in this cell is Georginio Wijnaldum
The value in this cell is NEW
The value in this cell is Midfielder
The value in this cell is 31
The value in this cell is 2705
The value in this cell is 17
The value in this cell is 345
The value in this cell is 23
The value in this cell is 167
The value in this cell is 10
The value in this cell is
                            512

The value in this cell is 13
The value in this cell is None
The value in this cell is 16
The value in this cell is Gylfi Sigurdsson
The value in this cell is SWA
The value in this cell is Midfielder
The value in this cell is 32
The value in this cell is 2571
The value in this cell is 16
The value in this cell is 202
The value in this cell is 13
The value in this cell is 306
The value in this cell is 19
The value in this cell is
                            508

The value in this cell is 14
The value in this cell is None
The value in this cell is 13
The value in this cell is Toby Alderweireld
The value in this cell is TOT
The value in this cell is Defender
The value in this cell is 32
The value in this cell is 2880
The value in this cell is 16
The value in this cell is 260
The value in this cell is 16
The value in this cell is 240
The value in this cell is 15
The value in this cell is
                            500

The value in this cell is 15
The value in this cell is None
The value in this cell is 17
The value in this cell is Cesc Fàbregas
The value in this cell is CHE
The value in this cell is Midfielder
The value in this cell is 30
The value in this cell is 2266
The value in this cell is 17
The value in this cell is 290
The value in this cell is 18
The value in this cell is 207
The value in this cell is 15
The value in this cell is
                            497

The value in this cell is 16
The value in this cell is None
The value in this cell is 15
The value in this cell is Olivier Giroud
The value in this cell is ARS
The value in this cell is Forward
The value in this cell is 31
The value in this cell is 1956
The value in this cell is 16
The value in this cell is 228
The value in this cell is 15
The value in this cell is 264
The value in this cell is 16
The value in this cell is
                            492

The value in this cell is 17
The value in this cell is None
The value in this cell is 28
The value in this cell is Alexis Sánchez
The value in this cell is ARS
The value in this cell is Forward
The value in this cell is 23
The value in this cell is 1826
The value in this cell is 21
The value in this cell is 211
The value in this cell is 19
The value in this cell is 278
The value in this cell is 23
The value in this cell is
                            489

The value in this cell is 18
The value in this cell is None
The value in this cell is 14
The value in this cell is Aaron Ramsey
The value in this cell is ARS
The value in this cell is Midfielder
The value in this cell is 25
The value in this cell is 2219
The value in this cell is 19
The value in this cell is 203
The value in this cell is 17
The value in this cell is 281
The value in this cell is 22
The value in this cell is
                            484

The value in this cell is 19
The value in this cell is None
The value in this cell is 18
The value in this cell is Daniel Drinkwater
The value in this cell is LEI
The value in this cell is Midfielder
The value in this cell is 30
The value in this cell is 2592
The value in this cell is 16
The value in this cell is 265
The value in this cell is 17
The value in this cell is 218
The value in this cell is 16
The value in this cell is
                            482

The value in this cell is 20
The value in this cell is None
The value in this cell is 20
The value in this cell is Marko Arnautovic
The value in this cell is STK
The value in this cell is Forward
The value in this cell is 29
The value in this cell is 2417
The value in this cell is 16
The value in this cell is 277
The value in this cell is 18
The value in this cell is 189
The value in this cell is 14
The value in this cell is
                            466

### Resources
http://stackoverflow.com/questions/30847117/web-scraping-table-data-in-python <br \>
http://stackoverflow.com/questions/22777187/nested-tags-web-scraping-python <br \>
https://www.quora.com/How-do-I-install-urllib-and-urllib2-for-Python-3-3-2 <br \>
https://www.youtube.com/watch?v=5GzVNi0oTxQ